services:
  postgres: # this is used as the host in your connection string 
    image: postgres
    container_name: 'postgres_container'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=learningbuddy321
      - POSTGRES_DB=db_learningbuddy
    volumes:
      - pgdata:/var/lib/postgresql/data # this is where your data persists in the container
    ports:
      - 5432:5432 # use this port in your connection string

  learningbuddy.api:
    image: learningbuddy.api
    build:
      context: .
      dockerfile: LearningBuddy.API/Dockerfile # the Dockerfile is stored in the API project
    ports:
      - 5000:80 # port mapping
      - 7276:443
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # debug runs in development mode
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=LearningBuddy # password used when making the cert, without curly braces
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      # - DatabaseType=Docker
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ~/.aspnet/https:/https:ro

volumes:
  pgdata: